### ISSUE TITLE
Login: Username field is not case sensitive

### ISSUE THREAD

**Issue by kingchua** [mgeronimo/ccb#17]
Steps to replicate:
1. Input username with different letter case
2. Input password
3. Click Sign In button

Expected: User should not be able to log in. User should be notified that the username is invalid/in a different letter case

Actual Result: User was able to login and was redirected to the dashboard

![ccb-login](https://cloud.githubusercontent.com/assets/12931347/9675223/439d5f98-52ed-11e5-817c-5e69f4663ed4.png)

**Comment by maarahoy** [comment]
Issue fix was verified
