### ISSUE TITLE
Add Group Mgt: Page proceeds to next step even if user entered spaces on supervisor's firstname and lastname

### ISSUE THREAD

**Issue by kingchua** [mgeronimo/ccb#21]
Steps to replicate:
1. Login as admin.
2. Click "Add Group" button.
3. Fill out step 1
4. Click "Next".
5. Enter space inputs in supervisor's firstname and last name.
6. Click "Next".

Expected result: Validation message indicating that the supervisor's firstname and lastname field is required

Actual result: Page proceeds to next step

![ccb-supervisordetails](https://cloud.githubusercontent.com/assets/12931347/9675516/15c315be-52f1-11e5-9664-08d966160ffc.png)

**Comment by shielanunez** [comment]
Issue was already fixed.
