### ISSUE TITLE
Add Group Mgt: Allows user to submit with spaces for the agent first and last name.

### ISSUE THREAD

**Issue by jmcmanzanilla** [mgeronimo/ccb#22]
Steps to replicate.
        1. Login as admin.
        2. Click on Add Group button. 
        3. Fill out Step 1 and 2. 
        4. Enter spaces for agent first name and last name.
        5. Enter agent email.
        6. Click on submit button.
Expected Result: Notify user that space inputs are not valid.
Actual Result: Allows user to sumbit and successfully add group with
![error ccb_2 1](https://cloud.githubusercontent.com/assets/13187770/9675468/6da305b0-52f0-11e5-88d0-e25f71c46381.png)
 space inputs for agent first name and last name.

**Comment by shielanunez** [comment]
Issue was already fixed.
