### ISSUE TITLE
Add Group Mgmt: User can add an Agent group with spaces inputs on Agent name

### ISSUE THREAD

**Issue by maarahoy** [mgeronimo/ccb#28]
Steps to replicate:
1. Login as administrator.
2. Click "Add Group".
3. Accomplish Step 1 and Step 2 with valid inputs.
4. Enter spaces on Agent Name with valid email address.
5. Click "Submit".

Actual result: User can add an Agent group with  spaces inputs on Agent name
Expected result: A validation message should appear indicates that the Agent name is required.  User should not be able to add an agent group. 
![spaces-agentname](https://cloud.githubusercontent.com/assets/12744684/9710467/4645052a-556d-11e5-8322-7119c0f115ae.png)

**Comment by shielanunez** [comment]
Issue can no longer be replicated.
