### ISSUE TITLE
Add Ticket (Mobile): Allows submission of tickets with space inputs for text fields

### ISSUE THREAD

**Issue by jmcmanzanilla** [mgeronimo/ccb#37]
Steps to replicate:
1. Log in mobile app.
2. Tap on "Add Ticket".
3. Fill up ticket form with spaces for inputs in text fields.
4. Submit form.

Expected result: User would be notified of invalid input and submission of form would not be successful.

Actual result: Ticket is successfully submitted.

**Comment by shielanunez** [comment]
Issue can no longer be replicated.
