### ISSUE TITLE
Possible department names will be lengthy but department name is has maximum of 45 characters only

### ISSUE THREAD

**Issue by shielanunez** [mgeronimo/ccb#5]
Note: This is a design and implementation issue.

*Possible department names will be lengthy. Thus, my question here is wouldn't it be better if we rather use this field for the department's short name and we'll add another field for it's description? This will also be useful for the mobile app since there is a feature for selecting a department. 

![image](https://cloud.githubusercontent.com/assets/7791554/9350122/35f4feec-4680-11e5-83e8-0e45f519c354.png)

**Comment by mgeronimo** [comment]
By "department's short name" you mean something like "DepEd" and "DOH", is that right? Sure, we can do that. What would be the maximum size of that column though?

**Comment by shielanunez** [comment]
Issue was already addressed in the latest db model - https://files.slack.com/files-pri/T077MA546-F09N5B1LK/ccb_datamodel_v3.png
